### ISSUE TITLE
Fix Footer for Mobile

### ISSUE THREAD

**Issue by Lemonsity** [Lodestone-Team/landing-page#16]
# Intention:
- Implement footer with better style when design arrives

# Why is it necessary:
- The current footer style on mobile is unnatural (as seen below)

![Image](https://user-images.githubusercontent.com/38927629/180575872-f3755ff2-af80-4608-b5d8-6968be2ab3c0.png)

**Comment by CheatCod** [comment]
Blocked by #14

**Comment by Ynng** [comment]
Enough is done of #14 that this can continue

**Comment by Ynng** [comment]
Duplicate with #33, closed
