### ISSUE TITLE
fix power manage section spacing

### ISSUE THREAD

**Issue by ludayu560** [Lodestone-Team/landing-page#17]
# Intention:
reduce spacing between the subsections in power manage section. 
could also make it dynamic

# Why is it necessary:

![Image](https://user-images.githubusercontent.com/87355725/180668840-3df7e24f-a73a-4888-9695-0d83035f569d.png)

current spacing is awkward and was for old placeholders.

**Comment by Ynng** [comment]
We actually just increased this.
The old spacing is way too tight.

See this for example.
 https://web.archive.org/web/20211007202129/https://webflow.com/nocodeconf
