### ISSUE TITLE
Code mobile design for navbar

### ISSUE THREAD

**Issue by CheatCod** [Lodestone-Team/landing-page#33]
# Intention:

![Image](https://user-images.githubusercontent.com/47200772/182996852-b12d08ff-60dd-4517-830f-8c9e6a0eb460.png)

Make the items more visible.

# Why is it necessary:

Accessibility and looks better

**Comment by Ynng** [comment]
This is a more complicated issue.
Our font is overall too small.
The original design is actually a lot bigger then what we currently have, and we need to discuss this sometimes with design

**Comment by Ynng** [comment]
Renamed issue as we have a mobile design now
