### ISSUE TITLE
Hide "Onboard Section" on mobile

### ISSUE THREAD

**Issue by Ynng** [Lodestone-Team/landing-page#7]
- [x] Have this section not show up at all on mobile (You can't set up a Minecraft server on your phone anyways)

What it looks like right now.
![Image](https://user-images.githubusercontent.com/44907675/179428085-06d4ca96-31af-4445-ac42-e6264a33716a.png)

**Comment by ludayu560** [comment]
added css @media query for when width is smaller than 700px.

**Comment by Ynng** [comment]
Wait where is this fixed?
Where's the code?
